name: Workflow de treinamento Caixa

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Mande um alo!
        run: echo "Olá Mundo"
      - run: ls -l
      - uses: actions/checkout@v6
      - run: ls -l
