name: Workflow de treinamento Caixa

on:
  workflow_dispatch:

jobs:
  greet:
    env:
        MY_ENV: "Caio Queiroz"
    runs-on: ubuntu-latest
    steps:
      - name: Mande um alo!
        run: echo "Olá Mundo"
      - run: ls -l
      - uses: actions/checkout@v6
      - run: ls -l
      - name: Execute um script multi-linha
        run: | 
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
